pipelines:
  - name: release_integration_env
    steps:
      - name: BuildAndPush
        type: Bash
        configuration:
          inputResources:
            - name: integrationEnvGit
              trigger: false
          integrations:
            - name: il_automation
            - name: entplus_deployer
            - name: releases_jfrog_io_deployer
          environmentVariables:
            NEXT_VERSION: 0.0.0
        execution:
          onStart:
            - update_commit_status integrationEnvGit --context "$step_name"
          onExecute:
            - cd $res_integrationEnvGit_resourcePath

            # Set env
            - export CI=true
            - export JFROG_BUILD_STATUS=PASS
            - export JFROG_CLI_BUILD_NAME=ecosystem-integration-env-release
            - export JFROG_CLI_BUILD_NUMBER=$run_number
            - export JFROG_CLI_BUILD_PROJECT=ecosys
            - export IMAGE_NAME=entplus.jfrog.io/ecosys-docker-local/jfrog-ecosystem-integration-env:$NEXT_VERSION

            # Configure git
            - git checkout master
            - git remote set-url origin https://$int_il_automation_token@github.com/jfrog/jfrog-ecosystem-integration-env.git

            # Make sure versions provided
            - echo "Checking variables"
            - test -n "$NEXT_VERSION" -a "$NEXT_VERSION" != "0.0.0"

            # Tag
            - git tag $NEXT_VERSION

            # Download and config JFrog CLI
            - curl -fL https://install-cli.jfrog.io | sh
            - jf c rm --quiet
            - jf c add internal --url=$int_entplus_deployer_url --user=$int_entplus_deployer_user --password=$int_entplus_deployer_apikey

            # Build docker image
            - docker build . -t $IMAGE_NAME
            - jf docker scan $IMAGE_NAME --fail=false --bypass-archive-limits=true

            # Push docker image
            - jf rt docker-push $IMAGE_NAME ecosys-docker-local
            - jf rt bag && jf rt bce
            - jf rt bp

            # Distribute release bundle
            - jf ds rbc "jfrog-ecosystem-integration-env" $NEXT_VERSION --spec="release/specs/prod-rbc-spec.json" --spec-vars="VERSION=$NEXT_VERSION" --sign
            - jf ds rbd "jfrog-ecosystem-integration-env" $NEXT_VERSION --site=releases.jfrog.io --sync

            # Set 'latest' tag in releases.jfrog.io
            - jf rt docker-promote jfrog-ecosystem-integration-env reg2 reg2 --copy --source-tag=$NEXT_VERSION --target-tag=latest --url=https://releases.jfrog.io/artifactory --access-token=$int_releases_jfrog_io_deployer_access_token

            # Push tag
            - git push --tags
          onComplete:
            - update_commit_status integrationEnvGit --context "$step_name"
